#!/bin/sh

# List of subdirectories to clean, ignoring .git folder and sort them
SUBDIRS=$(find . -type d -not -path '*/.git*' | sort)

# Iterate over the subdirectories
for dir in $SUBDIRS; do
	if [ -d "$dir" ] && { [ -f "$dir/Makefile" ] || [ -f "$dir/makefile" ]; }; then
        echo "Cleaning $dir"
        make -C "$dir" clean > /dev/null
    fi
done
